CREATE TABLE HABITACIONES(
id NUMBER(20,0),
idEspacio NUMBER(20,0),
idCategoria NUMBER(20,0),
capacidad NUMBER(20,0),
compartido CHAR(1) CHECK(compartido IN('Y','N'))
);

ALTER TABLE HABITACIONES
ADD CONSTRAINT FK_ESPACIOHABITACION
FOREIGN KEY(idEspacio) REFERENCES ESPACIOS(id);

ALTER TABLE HABITACIONES
ADD CONSTRAINT PK_HABITACION
PRIMARY KEY (id);

ALTER TABLE HABITACIONES
ADD CONSTRAINT FK_CATEGORIAHABITACION
FOREIGN KEY(idCategoria) REFERENCES CATEGORIASHABITACION(id);

ALTER TABLE HABITACIONES 
MODIFY compartido NOT NULL
MODIFY capacidad NOT NULL
MODIFY idEspacio NOT NULL
MODIFY idCategoria NOT NULL;

INSERT INTO HABITACIONES (id, idEspacio, idCategoria, capacidad, compartido)
VALUES (1,1, 1, 3, 'N');

INSERT INTO HABITACIONES (id, idEspacio, idCategoria, capacidad, compartido)
VALUES (2,1, 3,5, 'Y');
