CREATE TABLE CLIENTES(
id NUMBER(10,0),
idVinculo NUMBER(10,0),
documento NUMBER(10,0),
nombre VARCHAR2(50),
edad NUMBER(2,0),
direccion VARCHAR2(50)
);

ALTER TABLE CLIENTES
MODIFY documento NUMBER(10,0) NOT NULL; 

ALTER TABLE CLIENTES
MODIFY nombre VARCHAR2(20) NOT NULL; 

ALTER TABLE CLIENTES
MODIFY edad NUMBER(10,0) NOT NULL; 

ALTER TABLE CLIENTES
MODIFY idVinculo NOT NULL; 

ALTER TABLE CLIENTES
MODIFY documento UNIQUE; 

ALTER TABLE CLIENTES
ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (id);

ALTER TABLE CLIENTES
ADD CONSTRAINT FK_VINCULO
FOREIGN KEY(idVinculo) REFERENCES VINCULOS(id);

INSERT INTO CLIENTES (ID, IDVINCULO, DOCUMENTO, NOMBRE, EDAD, DIRECCION)
VALUES(1,1, 1020820731, 'David Niño', 21, 'cll 32#13-83');

INSERT INTO CLIENTES (ID,IDVINCULO, DOCUMENTO, NOMBRE, EDAD, DIRECCION)
VALUES(2,1, 1023956044, 'Nicolás Hernández', 21, 'cll 32#13-83');