CREATE TABLE SERVICIOS(
id NUMBER(20,0),
idEspacio NUMBER(20,0),
idCategoria NUMBER(20,0),
inicioHorario NUMBER(20,0),
finHorario NUMBER(20,0),
precioAdicional NUMBER(20,0),
descripcion VARCHAR2(100)
);

ALTER TABLE SERVICIOS
ADD CONSTRAINT FK_ESPACIOSERVICIO
FOREIGN KEY(idEspacio) REFERENCES ESPACIOS(id);

ALTER TABLE SERVICIOS
ADD CONSTRAINT FK_CATEGORIASERVICIO
FOREIGN KEY(idCategoria) REFERENCES CATEGORIASSERVICIO(id);

ALTER TABLE SERVICIOS
ADD CONSTRAINT PK_SERVICIOS
PRIMARY KEY (id);

ALTER TABLE SERVICIOS
MODIFY idCategoria NOT NULL;

ALTER TABLE SERVICIOS
MODIFY precioAdicional NOT NULL;

ALTER TABLE SERVICIOS
MODIFY descripcion NOT NULL
MODIFY inicioHorario NOT NULL
MODIFY finHorario NOT NULL;

INSERT INTO SERVICIOS (ID, IDESPACIO, IDCATEGORIA,FINHORARIO, INICIOHORARIO, PRECIOADICIONAL, DESCRIPCION)
VALUES(1,1, 11,20, 7, 120000, 'Jacuzzi');

INSERT INTO SERVICIOS (ID,IDESPACIO,IDCATEGORIA, FINHORARIO, INICIOHORARIO, PRECIOADICIONAL, DESCRIPCION)
VALUES(2,2, 11,20, 7, 0, 'LETRINA');
