CREATE TABLE OPERADORES(
id NUMBER(10,0),
idCategoria NUMBER(10,0),
nombre VARCHAR2(50),
registro NUMBER(20,0),
documento NUMBER(20,0)
);

ALTER TABLE OPERADORES
ADD CONSTRAINT FK_CATEGORIAOPERADOR
FOREIGN KEY(idCategoria) REFERENCES CATEGORIASOPERADOR(id);

ALTER TABLE OPERADORES
ADD CONSTRAINT PK_OPERADORES
PRIMARY KEY (id);

ALTER TABLE OPERADORES 
MODIFY nombre NOT NULL
MODIFY registro UNIQUE
MODIFY documento UNIQUE
MODIFY idCategoria NOT NULL;

INSERT INTO OPERADORES (ID, idCategoria, NOMBRE, REGISTRO, DOCUMENTO)
VALUES(1, 6, 'CityU', 123, 1453);

INSERT INTO OPERADORES (ID,idCategoria, NOMBRE, REGISTRO, DOCUMENTO)
VALUES(2, 1, 'Monserrate', 153, 1468);