CREATE TABLE RESERVAS(
id NUMBER(20,0),
idEspacio NUMBER(20,0),
idCliente NUMBER(20,0),
idColectiva NUMBER(20,0),
duracion NUMBER(20,0),
fechaInicio DATE,
cancelado CHAR(1),
precio NUMBER(20,0),
fechaReserva DATE
);

ALTER TABLE RESERVAS
ADD CONSTRAINT PK_RESERVAS
PRIMARY KEY (id);

ALTER TABLE RESERVAS 
MODIFY fechaInicio NOT NULL;

ALTER TABLE RESERVAS 
MODIFY duracion NOT NULL;

ALTER TABLE RESERVAS 
MODIFY fechaReserva NOT NULL;

ALTER TABLE RESERVAS 
MODIFY idCliente NOT NULL;

ALTER TABLE RESERVAS 
MODIFY idEspacio NOT NULL;

ALTER TABLE RESERVAS
ADD CONSTRAINT FK_ESPACIORESERVA
FOREIGN KEY(idEspacio) REFERENCES ESPACIOS(id);

ALTER TABLE RESERVAS
ADD CONSTRAINT FK_CLIENTERESERVA
FOREIGN KEY(idCliente) REFERENCES CLIENTES(id);

ALTER TABLE RESERVAS 
ADD CONSTRAINT CHECKBOOL CHECK(cancelado IN ('Y','N'));

INSERT INTO RESERVAS (ID, IDESPACIO, IDCLIENTE, IDCOLECTIVA, DURACION, FECHAINICIO, FECHARESERVA, PRECIO, CANCELADO)
VALUES(1, 1, 1, null, 2, TO_DATE('2015-12-12','YYYY-MM-DD'), TO_DATE('2015-11-02','YYYY-MM-DD'), 1000000, 'N');

INSERT INTO RESERVAS (ID, IDESPACIO, IDCLIENTE, IDCOLECTIVA, DURACION, FECHAINICIO, FECHARESERVA, PRECIO, CANCELADO)
VALUES(2, 2, 2, null, 2, TO_DATE('2015-12-22','YYYY-MM-DD'), TO_DATE('2015-10-12','YYYY-MM-DD'), 100000, 'Y');