CREATE TABLE ESPACIOS(
id NUMBER(20,0),
idOperador NUMBER(20,0),
capacidad NUMBER(20,0),
registro NUMBER(20,0),
direccion VARCHAR2(50),
tamaño NUMBER(20,0),
precio NUMBER(20,2),
fechaRetiro DATE
);

ALTER TABLE ESPACIOS
ADD CONSTRAINT PK_ESPACIO
PRIMARY KEY (id);

ALTER TABLE ESPACIOS
ADD CONSTRAINT FK_OPERADORESPACIO
FOREIGN KEY (idOperador) REFERENCES OPERADORES (id);

ALTER TABLE ESPACIOS
MODIFY  tamaño NOT NULL;

ALTER TABLE ESPACIOS
MODIFY  fechaRetiro NOT NULL;

ALTER TABLE ESPACIOS
MODIFY  capacidad NOT NULL;

ALTER TABLE ESPACIOS
MODIFY  precio NOT NULL;

ALTER TABLE ESPACIOS
MODIFY  idOperador NOT NULL;

ALTER TABLE ESPACIOS
MODIFY  registro NOT NULL UNIQUE;
ALTER TABLE ESPACIOS
MODIFY  direccion NOT NULL UNIQUE;

INSERT INTO ESPACIOS (ID, IDOPERADOR,CAPACIDAD, REGISTRO, TAMAÑO, DIRECCION, PRECIO,FECHARETIRO)
VALUES (1,2, 5, 13453, 50, 'cll21#12-2apto404', 500000, TO_DATE('2019-07-02','YYYY-MM-DD'));

INSERT INTO ESPACIOS (ID,IDOPERADOR, CAPACIDAD, REGISTRO, TAMAÑO, DIRECCION, PRECIO,FECHARETIRO)
VALUES (2,2, 5, 13454, 50, 'cll21#12-2apto403', 500000, TO_DATE('2019-09-18','YYYY-MM-DD'));