SELECT ID
FROM ESPACIOS
WHERE ID IN(SELECT TABLAESPACIOS.ID
FROM HABITACIONES,(SELECT ESPACIOS.ID
            FROM ESPACIOS, (SELECT *
            FROM OPERADORES
            WHERE IDCATEGORIA = 1) TABLAOPERADORES
            WHERE ESPACIOS.IDOPERADOR = TABLAOPERADORES.ID) TABLAESPACIOS
            WHERE HABITACIONES.IDESPACIO = TABLAESPACIOS.ID  AND HABITACIONES.IDCATEGORIA = 1)
    AND ID IN(SELECT ID
            FROM(SELECT ID, COUNT(ID) AS CONTEO
            FROM(SELECT TABLAESPACIOS.ID, SERVICIOS.IDCATEGORIA
            FROM SERVICIOS,(SELECT ESPACIOS.ID
            FROM ESPACIOS, (SELECT *
            FROM OPERADORES
            WHERE IDCATEGORIA = 1) TABLAOPERADORES
            WHERE ESPACIOS.IDOPERADOR = TABLAOPERADORES.ID) TABLAESPACIOS
            WHERE SERVICIOS.IDESPACIO = TABLAESPACIOS.ID  AND (SERVICIOS.IDCATEGORIA = 11))TABLACATEGORIAS
            GROUP BY TABLACATEGORIAS.ID)
            WHERE CONTEO = 1);
      !--  AND ID IN(SELECT DISTINCT ESPACIOS.ID
      !--      FROM ESPACIOS, RESERVAS
       !--     WHERE ESPACIOS.ID = RESERVAS.IDESPACIO 
      !--      AND RESERVAS.FECHAINICIO > TO_DATE('2019-01-01','YYYY-MM-DD') + 3 AND (RESERVAS.FECHAINICIO + RESERVAS.DURACION < TO_DATE('2019-01-01','YYYY-MM-DD')));