SELECT ID, RESERVAS.FECHAINICIO
FROM RESERVAS
WHERE RESERVAS.IDESPACIO = 1 AND RESERVAS.FECHAINICIO > TO_DATE('2019-01-01','YYYY-MM-DD') AND RESERVAS.CANCELADO = 'N'
ORDER BY RESERVAS.FECHAINICIO ASC;
                    
SELECT ID, RESERVAS.FECHARESERVA
FROM RESERVAS
WHERE RESERVAS.IDESPACIO = 1 AND RESERVAS.FECHAINICIO + RESERVAS.DURACION > TO_DATE('2019-01-01','YYYY-MM-DD') AND RESERVAS.FECHAINICIO <= TO_DATE('2019-01-01','YYYY-MM-DD') AND RESERVAS.CANCELADO = 'N'
ORDER BY RESERVAS.FECHARESERVA ASC;