SELECT *
FROM CLIENTES
WHERE ID NOT IN (SELECT DISTINCT CLIENTES.ID
            FROM CLIENTES, RESERVAS
            WHERE CLIENTES.ID = RESERVAS.IDCLIENTE 
                AND RESERVAS.IDESPACIO = 1);