SELECT ID, CASE WHEN INGRESOS IS NULL THEN 0 ELSE INGRESOS END AS INGRESOS
FROM OPERADORES LEFT OUTER JOIN (SELECT ESPACIOS.IDOPERADOR AS IDOP, SUM(RESERVAS.PRECIO) AS INGRESOS 
        FROM ESPACIOS INNER JOIN RESERVAS ON RESERVAS.IDESPACIO = ESPACIOS.ID
        WHERE RESERVAS.FECHAINICIO > TO_DATE('2017-01-01','YYYY-MM-DD')
        GROUP BY ESPACIOS.IDOPERADOR)TABLAINGRESOS ON OPERADORES.ID = TABLAINGRESOS.IDOP
ORDER BY OPERADORES.ID;