-- CON OR --

SELECT ID
FROM CLIENTES
WHERE ID IN (SELECT IDCLIENTE
            FROM    (SELECT IDCLIENTE, COUNT(MESES) AS CONTEO
                    FROM    (SELECT DISTINCT IDCLIENTE, (EXTRACT(MONTH FROM FECHARESERVA)+ EXTRACT(YEAR FROM FECHARESERVA)*12) AS MESES
                            FROM RESERVAS)
                    GROUP BY IDCLIENTE)
            WHERE CONTEO = (SELECT EXTRACT(MONTH FROM SYSDATE) - EXTRACT(MONTH FROM MIN(FECHARESERVA)) + (EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM MIN(FECHARESERVA)))*12
                            FROM RESERVAS))
    OR ID IN    (SELECT TABLACONTEOTOTAL.IDCLIENTE
                FROM    (SELECT IDCLIENTE, COUNT(ID) AS CONTEOTOTAL
                        FROM RESERVAS
                        GROUP BY IDCLIENTE) TABLACONTEOTOTAL,
                        (SELECT IDCLIENTE, COUNT(ID) AS CONTEOCOSTOSOS
                        FROM RESERVAS
                        WHERE IDESPACIO IN (SELECT ID
                                            FROM ESPACIOS
                                            WHERE PRECIO >= 450000)
                        GROUP BY IDCLIENTE) TABLACONTEOCOSTOSOS
                WHERE TABLACONTEOTOTAL.CONTEOTOTAL = TABLACONTEOCOSTOSOS.CONTEOCOSTOSOS
                        AND TABLACONTEOTOTAL.IDCLIENTE = TABLACONTEOCOSTOSOS.IDCLIENTE)
    OR ID IN    (SELECT TABLACONTEOTOTAL.IDCLIENTE
                FROM    (SELECT IDCLIENTE, COUNT(ID) AS CONTEOTOTAL
                        FROM RESERVAS
                        GROUP BY IDCLIENTE) TABLACONTEOTOTAL,
                        (SELECT IDCLIENTE, COUNT(ID) AS CONTEOCOSTOSOS
                        FROM RESERVAS
                        WHERE IDESPACIO IN (SELECT DISTINCT ESPACIOS.ID
                                            FROM ESPACIOS, HABITACIONES
                                            WHERE ESPACIOS.ID = HABITACIONES.IDESPACIO
                                                AND HABITACIONES.IDCATEGORIA = 3)
                        GROUP BY IDCLIENTE) TABLACONTEOCOSTOSOS
                WHERE TABLACONTEOTOTAL.CONTEOTOTAL = TABLACONTEOCOSTOSOS.CONTEOCOSTOSOS
                        AND TABLACONTEOTOTAL.IDCLIENTE = TABLACONTEOCOSTOSOS.IDCLIENTE);

-- CON UNION --

SELECT IDCLIENTE
FROM    (SELECT IDCLIENTE, COUNT(MESES) AS CONTEO
        FROM    (SELECT DISTINCT IDCLIENTE, (EXTRACT(MONTH FROM FECHARESERVA)+ EXTRACT(YEAR FROM FECHARESERVA)*12) AS MESES
                FROM RESERVAS)
        GROUP BY IDCLIENTE)
WHERE CONTEO = (SELECT EXTRACT(MONTH FROM SYSDATE) - EXTRACT(MONTH FROM MIN(FECHARESERVA)) + (EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM MIN(FECHARESERVA)))*12
                FROM RESERVAS)
UNION
SELECT TABLACONTEOTOTAL.IDCLIENTE
FROM    (SELECT IDCLIENTE, COUNT(ID) AS CONTEOTOTAL
        FROM RESERVAS
        GROUP BY IDCLIENTE) TABLACONTEOTOTAL,
        (SELECT IDCLIENTE, COUNT(ID) AS CONTEOCOSTOSOS
        FROM RESERVAS
        WHERE IDESPACIO IN (SELECT ID
                            FROM ESPACIOS
                            WHERE PRECIO >= 450000)
        GROUP BY IDCLIENTE) TABLACONTEOCOSTOSOS
WHERE TABLACONTEOTOTAL.CONTEOTOTAL = TABLACONTEOCOSTOSOS.CONTEOCOSTOSOS
        AND TABLACONTEOTOTAL.IDCLIENTE = TABLACONTEOCOSTOSOS.IDCLIENTE
UNION  
SELECT TABLACONTEOTOTAL.IDCLIENTE
FROM    (SELECT IDCLIENTE, COUNT(ID) AS CONTEOTOTAL
        FROM RESERVAS
        GROUP BY IDCLIENTE) TABLACONTEOTOTAL,
        (SELECT IDCLIENTE, COUNT(ID) AS CONTEOCOSTOSOS
        FROM RESERVAS
        WHERE IDESPACIO IN (SELECT DISTINCT ESPACIOS.ID
                            FROM ESPACIOS, HABITACIONES
                            WHERE ESPACIOS.ID = HABITACIONES.IDESPACIO
                                AND HABITACIONES.IDCATEGORIA = 3)
        GROUP BY IDCLIENTE) TABLACONTEOCOSTOSOS
WHERE TABLACONTEOTOTAL.CONTEOTOTAL = TABLACONTEOCOSTOSOS.CONTEOCOSTOSOS
        AND TABLACONTEOTOTAL.IDCLIENTE = TABLACONTEOCOSTOSOS.IDCLIENTE;