SELECT CATEGORIASOPERADOR.ID, SUM(RESERVAS.DURACION) AS DIASTOTAL, SUM(RESERVAS.PRECIO) AS DINEROTOTAL
FROM OPERADORES, ESPACIOS, RESERVAS, CATEGORIASOPERADOR
WHERE OPERADORES.ID = ESPACIOS.IDOPERADOR AND ESPACIOS.ID = RESERVAS.IDESPACIO AND CATEGORIASOPERADOR.ID = OPERADORES.IDCATEGORIA
GROUP BY CATEGORIASOPERADOR.ID
ORDER BY CATEGORIASOPERADOR.ID ASC;

SELECT ID, IDCATEGORIA
FROM (SELECT DISTINCT CATEGORIASOPERADOR.ID, SERVICIOS.IDCATEGORIA
FROM OPERADORES, ESPACIOS, SERVICIOS, CATEGORIASOPERADOR
WHERE OPERADORES.ID = ESPACIOS.IDOPERADOR AND ESPACIOS.ID = SERVICIOS.IDESPACIO AND CATEGORIASOPERADOR.ID = OPERADORES.IDCATEGORIA
ORDER BY CATEGORIASOPERADOR.ID ASC) WHERE ID = 1;