SELECT VINCULOS.ID, SUM(RESERVAS.DURACION) AS DIASTOTAL, SUM(RESERVAS.PRECIO) AS DINEROTOTAL
FROM CLIENTES, RESERVAS, VINCULOS
WHERE CLIENTES.ID = RESERVAS.IDCLIENTE AND CLIENTES.IDVINCULO = VINCULOS.ID
GROUP BY VINCULOS.ID
ORDER BY VINCULOS.ID ASC;

SELECT ID, IDCATEGORIA
FROM (SELECT DISTINCT VINCULOS.ID, SERVICIOS.IDCATEGORIA
FROM CLIENTES, RESERVAS, ESPACIOS, SERVICIOS, VINCULOS
WHERE CLIENTES.ID = RESERVAS.IDCLIENTE AND RESERVAS.IDESPACIO = ESPACIOS.ID AND ESPACIOS.ID = SERVICIOS.IDESPACIO AND VINCULOS.ID = CLIENTES.IDVINCULO
ORDER BY VINCULOS.ID ASC) WHERE ID = 1;