SELECT CLIENTES.ID, SUM(RESERVAS.DURACION) AS DIASTOTAL, SUM(RESERVAS.PRECIO) AS DINEROTOTAL
FROM CLIENTES, RESERVAS
WHERE CLIENTES.ID = RESERVAS.IDCLIENTE AND CLIENTES.ID = 1
GROUP BY CLIENTES.ID
ORDER BY CLIENTES.ID ASC;

SELECT DISTINCT CLIENTES.ID, SERVICIOS.IDCATEGORIA
FROM CLIENTES, RESERVAS, ESPACIOS, SERVICIOS
WHERE CLIENTES.ID = RESERVAS.IDCLIENTE AND RESERVAS.IDESPACIO = ESPACIOS.ID AND ESPACIOS.ID = SERVICIOS.IDESPACIO AND CLIENTES.ID = 1
ORDER BY CLIENTES.ID ASC;
