SELECT OPERADORES.ID, SUM(RESERVAS.DURACION) AS DIASTOTAL, SUM(RESERVAS.PRECIO) AS DINEROTOTAL
FROM OPERADORES, ESPACIOS, RESERVAS
WHERE OPERADORES.ID = ESPACIOS.IDOPERADOR AND ESPACIOS.ID = RESERVAS.IDESPACIO AND OPERADORES.ID = 1
GROUP BY OPERADORES.ID
ORDER BY OPERADORES.ID ASC;

SELECT DISTINCT OPERADORES.ID, SERVICIOS.IDCATEGORIA
FROM OPERADORES, ESPACIOS, SERVICIOS
WHERE OPERADORES.ID = ESPACIOS.IDOPERADOR AND ESPACIOS.ID = SERVICIOS.IDESPACIO AND OPERADORES.ID = 2
ORDER BY OPERADORES.ID ASC;