SELECT IDCLIENTE, DURTOTAL, CONTEO
FROM(SELECT RESERVAS.IDCLIENTE, SUM(RESERVAS.DURACION) AS DURTOTAL, COUNT(RESERVAS.ID) AS CONTEO
FROM RESERVAS, ESPACIOS
WHERE RESERVAS.IDESPACIO = ESPACIOS.ID AND RESERVAS.CANCELADO = 'N' AND ESPACIOS.ID = 2
GROUP BY RESERVAS.IDCLIENTE)
WHERE DURTOTAL >= 15 OR CONTEO >= 3;