SELECT * FROM(SELECT IDESPACIO, MAX(ESPACIODIAS) AS MAXIMOPERIODO
FROM (WITH FECHAS AS(SELECT ROWNUM AS ID, IDESPACIO, FECHAINICIO, DURACION
FROM(SELECT IDESPACIO, FECHAINICIO, DURACION
FROM RESERVAS
WHERE RESERVAS.CANCELADO = 'N'
ORDER BY IDESPACIO ASC, FECHAINICIO ASC))
SELECT T1.FECHAINICIO - (T2.FECHAINICIO + T2.DURACION) AS ESPACIODIAS, T1.IDESPACIO
FROM (FECHAS)T1, (FECHAS)T2
WHERE T2.ID = T1.ID -1 AND T2.IDESPACIO = T1.IDESPACIO)
GROUP BY IDESPACIO) WHERE MAXIMOPERIODO > 30;